"""align server defaults with the model

Revision ID: 5e1636c9c627
Revises: d219d06c6b9c
Created: 2026-08-19 04:40:10.629334
"""
from alembic import op
import sqlalchemy as sa


revision = '5e1636c9c627'
down_revision = 'd219d06c6b9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Give the columns the server-side defaults the model declares.

    Without them, autogenerate proposes dropping the one that does exist on
    every subsequent migration — churn that eventually gets applied, leaving a
    NOT NULL column with nothing to fill it for any INSERT not written by
    SQLAlchemy.

    PostgreSQL only. SQLite has no ALTER COLUMN, and does not need one here:
    the test suite builds its schema from the model directly, so the Python
    default already applies.
    """
    if op.get_bind().dialect.name != "postgresql":
        return

    for column in ("crypto_replacements", "reversal_attempts"):
        op.alter_column(
            "transactions",
            column,
            existing_type=sa.INTEGER(),
            server_default="0",
            existing_nullable=False,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'reversal_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'crypto_replacements',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
