"""add transactional outbox

Revision ID: 7cd4abcf0edc
Revises: 7a2c4f9b1d33
Created: 2026-08-18 05:25:30.333824
"""
from alembic import op
import sqlalchemy as sa


revision = '7cd4abcf0edc'
down_revision = '7a2c4f9b1d33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('countdown', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('abandoned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_pending', 'outbox', ['published_at', 'abandoned', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_pending', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
