"""initial schema

Revision ID: 5e11e7026cb2
Revises: 
Created: 2026-08-17 23:27:36.440626
"""
from alembic import op
import sqlalchemy as sa


revision = '5e11e7026cb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('masked_pan', sa.String(length=19), nullable=False),
    sa.Column('target_wallet', sa.String(length=42), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FIAT_APPROVED', 'FIAT_DECLINED', 'CRYPTO_SENT', 'CRYPTO_FAILED', 'REVERSED', 'REVERSAL_FAILED', 'FIAT_UNKNOWN', name='transactionstatus'), nullable=False),
    sa.Column('stan', sa.String(length=6), nullable=True),
    sa.Column('rrn', sa.String(length=12), nullable=True),
    sa.Column('auth_code', sa.String(length=6), nullable=True),
    sa.Column('action_code', sa.String(length=3), nullable=True),
    sa.Column('crypto_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('crypto_amount_units', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('crypto_nonce', sa.Integer(), nullable=True),
    sa.Column('crypto_replacements', sa.Integer(), nullable=False),
    sa.Column('reversal_stan', sa.String(length=6), nullable=True),
    sa.Column('reversal_attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_crypto_tx_hash', 'transactions', ['crypto_tx_hash'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_stan', 'transactions', ['stan'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_status_created_at', 'transactions', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_status_created_at', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_stan', table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('ix_transactions_crypto_tx_hash', table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
