"""record capture stan before sending

Revision ID: b493a9bd1de4
Revises: 7cd4abcf0edc
Created: 2026-08-18 22:45:01.656780
"""
from alembic import op
import sqlalchemy as sa


revision = 'b493a9bd1de4'
down_revision = '7cd4abcf0edc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('capture_stan', sa.String(length=6), nullable=True))
    op.add_column('transactions', sa.Column(
            "capture_attempts",
            sa.Integer(),
            nullable=False,
            # PostgreSQL refuses a NOT NULL column on a table that already has
            # rows unless it can fill them. Autogenerate omits the default, so
            # the migration passes on an empty database and fails on a
            # production one — the worst place to discover it.
            server_default="0",
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'capture_attempts')
    op.drop_column('transactions', 'capture_stan')
    # ### end Alembic commands ###
