"""lock exchange rate at authorisation

Revision ID: d219d06c6b9c
Revises: b493a9bd1de4
Created: 2026-08-19 04:37:46.384216
"""
from alembic import op
import sqlalchemy as sa


revision = 'd219d06c6b9c'
down_revision = 'b493a9bd1de4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('exchange_rate', sa.Numeric(precision=28, scale=12), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate_source', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate_at', sa.DateTime(timezone=True), nullable=True))
    # Autogenerate proposed dropping capture_attempts' server default here.
    # Deliberately not done: the model now declares it, so the two agree and
    # the proposal does not recur. Dropping it would leave a NOT NULL column
    # with nothing to fill it for any INSERT not written by SQLAlchemy.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'capture_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_column('transactions', 'exchange_rate_at')
    op.drop_column('transactions', 'exchange_rate_source')
    op.drop_column('transactions', 'exchange_rate')
    # ### end Alembic commands ###
